steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - bff_protocol=${_BFF_PROTOCOL}
      - --build-arg
      - bff_base_domain=${_BFF_BASE_DOMAIN}
      - --build-arg
      - be_protocol=${_BE_PROTOCOL}
      - --build-arg
      - be_base_domain=${_BE_BASE_DOMAIN}
      - -t
      - gcr.io/myrecord-376903/myrecord-web-application
      - .
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myrecord-376903/myrecord-web-application']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'myrecord-web', '--image', 'gcr.io/myrecord-376903/myrecord-web-application', '--region', 'asia-northeast1']
substitutions:
  _BFF_PROTOCOL: https # default value
  _BFF_BASE_DOMAIN: myrecord-web-tyqu5egcpq-an.a.run.app
  _BE_PROTOCOL: https
  _BE_BASE_DOMAIN: myrecord-rest-api-tyqu5egcpq-an.a.run.app
images:
  - gcr.io/myrecord-376903/myrecord-web-application